name: pullrequest_check
on:
  pull_request

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - run: npm install
      - run: npm run build
